project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: experience.qmd
        text: Experience
      - href: projects.qmd
        text: Projects
    right: 
      - icon: github
        menu: 
          - text: Website Source Code
            url: https://github.com/shiyu-m/personal-website
          - text: GitHub Profile
            url: https://github.com/shiyu-m
  page-footer:
    right: "&copy; 2024, Shiyu Murashima"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute: 
  freeze: auto


